### ISSUE TITLE
XSS-hyökkäys lähettämällä kustomoitu POST-pyyntö

### ISSUE THREAD

**Issue by Asdew95** [kaikkitietokoneista/kaikkidokumentit#1]
Normaalin POST-pyynnön datasave-parametriä ei ole suojattu XSS-hyökkäyksiltä, joten esimerkiksi tämä datasave-parametri aiheuttaa XSS-hyökkäyksen kun dokumentti avataan:
`<script>alert("XSS");</script>`
Tätä ei tietääkseni voi aiheuttaa pelkällä nettikäyttöliittymällä, mutta esimerkiksi Firefoxin tarkastelutyökalulla pystyy saada hyökkäyksen tehtyä.

**Comment by RoyTakanen** [comment]
Kiitos @Asdew95. Parannamme koodiamme välittömästi.

**Comment by RoyTakanen** [comment]
Korjattu lähettämälläsi koodilla. Kiitos @Asdew95.
